### ISSUE TITLE
Custom decompiler tool chain

### ISSUE THREAD

**Issue by kevinferrare** [OpenDUNE/OpenDUNE#288]
Looking at the early commits, it is my understanding that this code base started as a decompilation of the original dune.exe:
https://github.com/OpenDUNE/OpenDUNE/blob/d73eef6f5334a00efbfd9080176860eb6a23366a/decompiled/cs__0070.c

This decompile process seems quite interresting for old 16 bit DOS binaries because as far as I understand, it allows to get a working 32/64bit exe on the top of SDL / libemu (customized).
With a working exe, rewriting bit by bit the decompiled code seems to be much less of an hassle than with other conventional methods.

As far as I could see, those tools are not listed anywhere, which is a pity considering the potential they have to recover old dos binaries for which source code has been lost.
Does anyone know where they can be found?

**Comment by TrueBrain** [comment]
It was a very interesting time, I can tell you :) Pretty fun hobby project that resulted in something real.

What for me the most interesting was of the approach, that it was both a static decompiler as a runtime. This combination resulted in very solid results, for a good amount of 16-bit realmode DOS games. And maybe more interesting how hard those old games tried to avoid being decompiled :D

The tools used were fully written from scratch; both the decompiler (named 'toc') as the emulation library (named 'libemu'), which just emulated DOS (software) and IBMPC (hardware) for as far as the games needed. It only implemented 16bit instruction set, and a few 32bit; but never any of the protected mode stuff. It could emulate most of the CGA / EGA / VGA, as long as it stayed in the lower memory.

I often used DOSBox as inspiration how to solve certain nuances in implementations. And I even went as far as compiling a few of these games on an FPGA, just because you can.

Out of the tons of games I fiddled with, Dune2 stuck with me, and with the help of a few people resulted in this Open Source project. And indeed, having a functional, compileable, playable game all the time really helped in the process.

That said, some of the tools are (no longer) publicly available, and some were never published to start with. This because of the obvious potential of abuse (reverse-enginering is illegal by law in most countries); this made me reluctant to do so. There is this thin line, and I always found it hard to stay on the right side.
Also, I think DOSBox does a fine job emulating most of the old DOS games out there. The only potential I could see for a toolchain like this, is to help companies who long lost their source code for some mission critical piece of software; but so far nobody asked for that situation :D Most just wanted to decompile their favorite game.

I used to write blog posts explaining what I did and how it all works and connects together, but both the blog and forum died a silent death years ago, together with the source of both 'toc' as 'libemu'. I once had plans to rewrite the whole toolchain to allow support of more instruction-sets, hardware, and Operation Systems, but it never got of the ground.

So making a long story short: no, the tools are no longer publicly available. Sorry :( If you have any specific questions or want to know more etc, feel free to reply or drop me an email. And tnx for the interest; 8 years ago .. time flies :D

**Comment by miniupnp** [comment]
@TrueBrain the blog is not available through www.archive.org ?

**Comment by kevinferrare** [comment]
Wow thank you for your reply! I wasn't expecting to a feedback so fast, especially with such an amount of information!
I can believe you had a lot of fun doing this, especially with the results you achieved!

It is too bad that you lost your tools. For the geek in me, this part of the opendune project is by far the most interresting.

Apart from the "gray" realm of the decompilation of abandonwares, there are other area where this technique could be used for perfectly legal reasons, tools are just tools :)
I took a look at the blog posts you made on opendune.org, and on the few other places as well (thanks archive.org!), but the details are too scarce, and the only way I found to contact you was through this bugtracker :P

By the way, I would like to hear more, but I don't know you email address. My address is my username @gmail.com. Too bad github does not allow PM between members.

**Comment by TrueBrain** [comment]
Sorry for not emailing; life has been hectic (as it goes). If you still have any more questions or anything else, feel free to drop an email: truebrain at opendune dot org.

I would love to hear btw what you are planning to use such tooling on :)

**Comment by kevinferrare** [comment]
Hey Patric, thanks for your message!

Life has been very busy for me as well those last months.
Drop me an email if you would like to hear more!
