### ISSUE TITLE
Decompiler thought process

### ISSUE THREAD

**Issue by timedumper** [OpenDUNE/OpenDUNE#300]
I want to start a similar project for an old Win32 game from 1998. In this case no hardware emulation should be needed as the original executable is running fine on Wine which means that in theory all system calls can be implemented by calling appropriate function in wine emulated layer.

I still don't understand how one would go about creating a working, compilable equivalent of the original game. I tried browsing some old commits and searching web archive as advised in #288 but didn't get too far with that.

I would appreciate if @TrueBrain or somebody with good knowledge of this project matter share their thoughts on possible approaches. How did you guys do it for OpenDUNE? 

What static analysis tools did you use to isolate functions and what do you mean by second stage (what was the first stage?): `bfc7635a -Add: initial set of stat-files for the static analyser (second stage of decompiler)` 

What were you referring to as JIT in some old commit messages (e. g. `1cff0793 -Add (r59): the decompiled code reflecting latest JIT data`)? 

How would you go about converting a Win32 exec into a decompiled version of itself that functions just like the original game, calling the same win32 apis and keep running it under wine?

**Comment by TrueBrain** [comment]
Besides what I wrote in #288, there is not much more to add. Except for a lot of time, there is not a magic bullet here.

That said, I can explain a bit more about your specific question, but it is over 10 years ago, so my memory can be a bit fuzzy in those regards.

JIT: how the processed worked, is that we started the game in an emulator, where you had to hit as many code-paths as possible. In the background, the emulator was recording all instructions it found, up to the next branch it hit. Then it waited for the code to hit that branch, and tell it where it was going to. Recorded the destination, and repeat. A long and length process to hit all parts.

Commit 1cff0793 is such commit, where we played the game a bit more in the emulator, hit a few more branches, and recompiled C code based on that. You can see it removed a lot of: `unresolved jump`.

Often when making the C code more readable, we found how we could trigger the different branches (as we understood the code that was there), and started to game to specifically find these parts. This is also how we found a lot of bugs, and other fun stuff :D

Basically, this is how the whole project was build up. Partially static decompiling, partially runtime.

How the emulator worked, is that it read the bytes from (virtual) memory, decoded the opcodes up till the next branch, and emulated those opcodes (in a bit of clever way). This was only done for snippets which it hadn't seen yet.
So, this was nicked the JIT, as it is basically Just-In-Time read the next part of the game if it didn't know that. Bit reverse of your classical JIT, but you get the idea. In this first stage, no C code was ever created.

The above is not the full story. As it goes, it is a lot more complicated. What the JIT does when it found new code it hadn't seen before, is poop out stat files like in bfc7635a. In these files is some basic information, and the bytecode.

Another tool processed these files, and could make C out of it. This was done staticly (without running the game in any shape or form), as the runtime part was done. So the first stage was mostly the JIT (and some other stuff), running the game, etc. The second stage was creating C code out of the bytecode.

Both tools had their own domain, and had little to do with each other (except for exchanging this information). This was mostly done as we slowly converted the C code to more readable C code. The decompiler had to understand if new information from the JIT came in, what parts to pick from the already rewritten C code, and which to regenerate. This was part of the second stage. This meant the first stage could still do its own trick, and didn't care about what happened after. A bit like intermediate bytecode, like we are more used to now in 2018 :) I think none of the other contributors ever really dared to touch the JIT part, except for `glx` for small snippets. It was complex and difficult to handle (and error-prune, I guess). But the second stage we all used, as we had to do our bookkeeping (write down which address you rewrote to better-readable-C, so the second stage didn't overwrite it). Now come to think of it, this is most likely why the tool was named `toc`, as I think it stands for `To C`. How basic :)

We ended up with tons and tons and tons of text files like in bfc7635a., Each described exactly one code path up till the next branch, created by the JIT. toc processed these files.

This is just one way of approaching such problem btw. I am sure others came up with better methods in the last 10 years (at least, I really hope so :D). I know there are several decompilers which do a good job, but it heavily depends on how your executable was created (read: by which tools). And of course you always have IDA!

Btw, the easiest part of the project was transforming the bytecode to C code .. we just looked up the bytecode to its opcode, and write a C function for every possible opcode we supported. For example: `mov ax, bx` simply became: `mov(reg_ax, reg_bx)`, in the initial version .There is nothing more to that, except for bookkeeping. This is what the second stage mainly did.

Hope this helps a bit. It is very complex stuff, and I used to have a blog which explained most of it .. but alas .. it seems to be lost. So far nobody gave me any incentive to look up and write out (again?) how everything works, as I am still having a hard time seeing how it can be used for good, more than used for bad. But as you can see, I have little issues answering specific questions.

I guess for anyone trying to recreate such a tool, it is important to understand the full chain, and sit down and think how it could be working. A lot of good tools give tons of examples (DOSBox, Wine, or even QEMU), on how it could work.

Right, I think I rambled enough for one day; I hope it is coherent enough and helps you out a bit :D Sorry if this isn't what you were hoping for :)

**Comment by TrueBrain** [comment]
Owh, I forgot to add to #288, you can always contact me via truebrain at opendune dot org. Feel free to email about specifics, but I also do like doing these things in public, as others might be interested as well.

**Comment by timedumper** [comment]
Fascinating! I'll definitely be back with follow up questions as I want to fully comprehend the workflow and toolset. This would be for an old RPG: https://en.wikipedia.org/wiki/Rage_of_Mages

It's quite old but not that old, so it's using Win32 APIs and is written in MSVC.

**Comment by timedumper** [comment]
I think emu_call was doing something other than quitting as [this macro](https://github.com/radekp/libemu/blob/d099cd2d7326947acd695e5076083585906d8040/src/libemu_call.h) defines... Is there an actual libemu source code in the wild? I couldn't find any...

**Comment by sonicpp** [comment]
Hey there,
I do not have much experince with decompilling, but IDA Free worked damn well for me (I was playing with Vietcong, the 3D game from 2003). It also runs well in Wine. You can have a look at some other projects in early stage,  [Bright-Eyes](https://github.com/Henne/Bright-Eyes) for example

**Comment by timedumper** [comment]
@sonicpp thanks... as I understood that project is about manually diverting the original game control flow to reverse-engineered high-level functions. In the end this might allow to ditch emulator and go native, but getting there requires good knowledge of assembly and low level debugging, is that right? 

What I would like to have is to create a decompiled version of the game and a documented setup which would allow anybody who knows C to just step through the game in the debugger (not just IDA, but any C-debugger of your choice), set breakpoints etc all from your favorite IDE on any OS (mac/win/linux). I might even change decompiler to produce higher level code if that will increase readability and lower the entry bar... 

The game is quite big and I'm pretty sure I won't be able to reverse all of it on my own, so I want to get it to a point where the bar for jumping on the whole reverse train is as low as possible. My hope is that this might attract more people from community to help me finish it.

**Comment by sonicpp** [comment]
@timedumper my understanding about bright-eyes is the same. Few months ago I started rewriting disassembled code of my favorite game. It was fun and I learned a lot about C and assembler. But you are right, it is not one-man project. So I started thinking about writing new code from scratch, like OpenMW or WINE, without knowledge of disassembled code (see [Clean room design](https://en.wikipedia.org/wiki/Clean_room_design)). Disadvantage of this process is that your project will not be binary the same with the original game. Advantage is that it does not break any copyright. If I understand it well. As I said, I am newbie in this.

**Comment by TrueBrain** [comment]
It seems the company that developed that game are still in business; did you try to contact them? You can either ask them if they don't mind if you reverse engineer their game, or if they might want to make the source public. It might help you out :) And just as a reminder, reverse engineering (a bit depending on your goal) is mostly considered illegal; so having the developers on your side can avoid nasty take-down notices after months of hard work ;)

That said, lets see about your questions ...

libemu is a library that supports the emulation process. Nothing more to it than that basically. So for example it could execute `mov_ax()` and `inb(port)`, and stuff like that. So the JIT generated those txt files, ToC generated C from that, which called functions defined in libemu. Then slowly we could rewrite those C functions to not use libemu, and slowly we removed the need for libemu completely.

If I remember correctly, the JIT didn't stop on a `call`, but ran till either a `ret` or a `jmp`. And it marked things like `call` and conditional jumps as like in your example, that the jump didn't resolve (yet). Basically, the JIT tried to decompile as many instructions it was 100% sure would be correct. Then I know of a few decompiler protections which even fooled this concept, but that was mainly for applications that wrote a few bytes away from the current `cs:ip`. With pages marked as executable in modern (protected memory) applications, those tricks went away. But this is a bit besides the point here :)

The other thing about the JIT, it creates a new txt file for every segment (from start till it hits a `ret` or `jmp`). ToC can merge segments together if it understand that it should.

The snippet from your example misses an important part: the part you omitted for brevity. I didn't check, but I am pretty sure that earlier there would have been a conditional jump the code did take. An the part you are seeing here is a part that was never seen in runtime. So, to explain a bit in detail:

During runtime the code jumped to `01F7:0028:001C;CF03`. The comment says it came from `01F7:0028:001C:2E35`, and that was the only place calling it at that point in time.

That chunk of code that was at that location had no `ret`, and ended with the `jmp` you showed. It can decode all instructions up till that point, and ToC generates C code from it.

Now somewhere in that function the runtime jumped to another place. Not a `call` , as a `call` always returns, but a conditional jump. And that jump never returned (at least, not during this runtime).

So, the JIT did record the whole function, but could only resolve that one jump pretty early in the function. It never hit any of the `jae` or `jmp` at the bottom, so it never got resolved.

In other words, what I try to say with many words: the JIT only resolves jumps it has seen. If it didn't see the jump, it also never executed it.

There are a few bits that will contradict the above, as compilers (and CPUs) can do some nasty stuff, but that is not the case with the 01F7 routines (which are core-routines, things like opening files, etc). Comparable with a `libc` these days. And for most part of such applications (read: 99%) the above method works and holds.

I find it odd that you cannot find the libemu source, while you point to an URL containing it. No clue where they got it from .. but yeah .. weird question there :P

`emu_call` is a bit of an odd one. It can be a `call`, a `jmp` or any conditional jump, if my memory serves me right.
Normally, if ToC can resolve the place you are going to jump to, it adds the C function there, a direct call. Like you can see in 1cff0793, where a few jumps are resolved.
Now in case it cannot resolve, you still want to know where it tried to jump to, so you can investigate. At that moment all things are set as they should (`ip`, `cs`, etc), and `emu_call` was called.
Now after compiling the C and hitting that `emu_call`, this always ended up in the application halting. BUT! It did something special:

It left a memory dump and some other magic for the JIT to pick up; you could run the JIT in a special mode that it picked up the memory dump and continue where the C version couldn't. This method wasn't 100% correct, and it could fuck up from time to time; the reason we didn't use it as much. But that was the general idea behind it. And because 16bit application cannot use more than 1 MiB of memory, the crash dumps were small enough to handle nicely. Basically the full emulation was dumped to disk. But from the C world. Not the JIT. (those are 2 worlds .. hard to keep them apart :D)

Now this isn't the full story, as libemu was also used by the JIT, which also handled stuff like `call`. But this is not the `emu_call` you see in the C code. (but `emu_calli`/`emu_calln`/`emu_callf`, depending on the `call` instruction (incremental?, near, and far).

Now your next question, about chunks, there it gets a bit complicated. Both the JIT and ToC tried to be 'smart'. It is pretty normal that stuff jumps into your function mid-ways, especially for compilers back then. Think about `while` and `for`. So what you got is something like:

```
chunk1a:
  emu_op1();
  emu_op2();
chunk1b:
  emu_op3();
  emu_op4();
```

Or it could make functions out of that:

```
void chunk1a() {
  emu_op1();
  emu_op2();
  chunk1b();
}
void chunk1b() {
  emu_op3();
  emu_op4();
}
```

But there were cases that this causes a bit of an issue with the stack-depth (as I mentioned earlier, jumps never return, so your stack depth can get pretty deep). Other times ToC just creates `chunk1` and `chunk1b`, and doesn't care they both have similar code.

It depends a bit how the code paths got discovered; I don't know anymore how it did its job in the end (it changed a few times over time :D), but I do remember it tried to detect if stuff was a loop, an `if`, etc. The later versions of ToC could even generate `if` blocks correctly. It is a bit of cooperation between the JIT and ToC there. JIT was the most naive, but ToC could see if chunks overlapped, and tried to make pretty C from it.

Fun fact, in these old days it happened often enough that the `chunk1b` call found other opcodes, despite being on the same memory location ... ugh ... those days :P

To close it up, IDA is not a debugger as such. It can really generate C code from your application (try it, there is a free IDA version with limited functionality). The main difference with my approach, and why IDA doesn't really work for old 16bit applications: it does it all by just looking at the executable (static decompiling). You have to fix a lot of assumptions before it works. As I hinted about earlier, it happens a lot that code blocks are changed during execution. IDA doesn't pick this up if it doesn't understand the compiler, and you have to fix that yourself. My method does pick that up, as it looks what happens runtime. But for that you have to start the application. IDA never has to. I love IDA .. such a nice and good tool :)

But I agree with the words of @sonicpp: if you want your open source game to work, think hard about reverse engineering without consent of the copyright holders; it might be a cold shower if you underestimate that. Stuff like Clean Room design helps to overcome that issue, but requires a few more dedicated people :)

As a reference, for OpenDUNE I sent out several letters to several companies which might or might not hold the copyright to Dune2 code, to ensure I was not creating an issue for myself. And I always said, and still saying: the moment someone drops me a word that they have the copyright and don't like this project, it is gone.
Sadly, in the case of Dune2, nobody seems to know which company holds the copyright .. and they all point to each other :P But I did try to reach out, before I started this project. I cannot urge you enough to do the same ;)

Other things to remember, copyright is not the same as distribution rights. And most companies don't really care about projects like this as long as they are not out to make a profit (or cut profit from their products). This game (OpenDUNE) is free: nobody is making any money on it what so ever (in fact, it costs money to keep the domain `opendune.org` :P), and if anything it keeps the good spirit of an old game alive :)
Again, please don't underestimate the importance of this :) Well, enough about legal bla :P

I think I covered all of your questions :) Hope it helps! Let me know if you have any more :)

**Comment by timedumper** [comment]
Thank you @TrueBrain, it all makes much more sense now. 

P. S. I was able to google up *some* sources of libemu (of unknown origin), but didn't check the state of things they were in. So yeah, I'm good now.
