### ISSUE TITLE
Make install instructions clearer

### ISSUE THREAD

**Issue by esn83** [OpenDUNE/OpenDUNE#379]
Installation & Running
----------------------
Extract OpenDUNE.
Copy the original Dune2 1.07 data files (including dune2.exe) to data/.
 All three existing versions of the Dune 1.07 data files (eu, hs and us) will
  work, but only with the eu/hs data files the French language will work, and
  only with the eu data files the German language will work.
Start 'opendune'.

Where is 'opendune' located?
The only ones I can find is /src/opendune.h and opendune.c.
If it's one of them how do I run them?

**Comment by codeflorist** [comment]
It seems you have downloaded the source code. Download the release suited for your system from here instead:
https://github.com/OpenDUNE/OpenDUNE/releases

**Comment by esn83** [comment]
Thanks, but I still think the issue is valid.
The link you supplied is nowhere to be found in the readme where the install instructions are.

**Comment by adrylain** [comment]
I agree. This issue is relevant and should be addressed. It is very important that there be documentation on compilation.

**Comment by Xaroth** [comment]
Hi,

The readme is packaged along with the releases. The source packages also include it because the readme is also kept under version control, just like the source code.

The source code packages, however, are not intended for non-developer users, as it requires some setup to be able to compile the binaries.
